server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml

security:
  oauth2:
    client:
      client-id: spring-boot-web-client
      client-secret: 123123
      refresh-token-validity-seconds: 50000
      access-token-validity-seconds: 1200
      grant-type: password
    resource:
      filter-order: 3


