# 配置服务相关信息
server:
  port: 9999

encrypt:
  key-store:
    location: mytest.jks
    secret: mypass
    alias: mytest

management:
  security:
    enabled: false

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

# mybatis配置文件
mybatis:
  mapper-locations: mapper/*.xml



